import { test, expect } from "@playwright/test";
import { createClient } from "@supabase/supabase-js";
import { execFileSync } from "node:child_process";
import { readFileSync } from "node:fs";
import path from "node:path";

const config = JSON.parse(execFileSync(process.execPath, ["node_modules/supabase/dist/supabase.js", "status", "-o", "json"], { encoding: "utf8", stdio: ["ignore", "pipe", "pipe"] }));
if (!["localhost", "127.0.0.1"].includes(new URL(config.API_URL).hostname)) throw new Error("Local tests only");
const credentials = JSON.parse(readFileSync(".local/review-access.json", "utf8"));
const admin = createClient(config.API_URL, config.SERVICE_ROLE_KEY, { auth: { persistSession: false } });
const title = `Gallery test ${Date.now()}`;
let productId: string;

test.afterAll(async () => {
  if (!productId) return;
  const { data: files } = await admin.storage.from("product-images").list(productId);
  if (files?.length) await admin.storage.from("product-images").remove(files.map(file => `${productId}/${file.name}`));
  const { error } = await admin.from("products").delete().eq("id", productId);
  if (error) throw error;
});

test("five-image gallery preserves existing images, order, retry and storefront cover", async ({ page }) => {
  const { data: options } = await admin.from("catalog_options").select().eq("active", true);
  const optionIds = Object.fromEntries(["artist", "genre", "format", "media_condition", "sleeve_condition"].map(kind => [`${kind}_id`, options!.find(option => option.kind === kind)!.id]));
  const created = await admin.from("products").insert({ ...optionIds, title, slug: `gallery-${Date.now()}`, artist: "", album: title, status: "published" }).select().single();
  if (created.error) throw created.error;
  productId = created.data.id;
  await page.route("**/*", async route => {
    if (new URL(route.request().url()).hostname.endsWith("supabase.co")) throw new Error("No production access in tests");
    await route.continue();
  });
  await page.goto("/admin/");
  await page.getByPlaceholder("Email admin").fill(credentials.email);
  await page.getByPlaceholder("Password", { exact: true }).fill(credentials.password);
  await page.getByRole("button", { name: "Entrar", exact: true }).click();
  await page.getByPlaceholder("Buscar producto...").fill(title);
  const row = page.locator(".admin-row");
  await expect(row).toHaveCount(1);
  const editor = row.getByRole("region", { name: "Imágenes del disco" });
  const files = [2273,2274,2275,2276,2277,2278].map(n => path.resolve(`public/products/IMG_${n}.jpg`));
  await editor.getByLabel("Imágenes", { exact: true }).setInputFiles(files);
  await expect(page.getByRole("alert", { name: "Notificación" })).toContainText("hasta 5 imágenes");
  await expect(editor.locator("li")).toHaveCount(0);
  await editor.getByLabel("Imágenes", { exact: true }).setInputFiles(files.slice(0,2));
  await expect(editor.locator("li")).toHaveCount(2);
  await row.getByRole("button", { name: "Guardar", exact: true }).click();
  await expect(page.getByText("Cambios guardados", { exact: true })).toBeVisible();
  const originalPaths = (await admin.from("product_images").select().eq("product_id", productId).order("sort_order")).data!.map(image => image.storage_path);
  await page.reload();
  await page.getByPlaceholder("Buscar producto...").fill(title);
  await expect(editor.locator("li")).toHaveCount(2);
  await editor.getByLabel("Imágenes", { exact: true }).setInputFiles(files.slice(2,5));
  await expect(editor.locator("li")).toHaveCount(5);
  await expect(editor.getByLabel("Imágenes", { exact: true })).toBeDisabled();
  await editor.getByRole("button", { name: "Mover imagen 2 antes", exact: true }).click();
  const dataTransfer = await page.evaluateHandle(() => new DataTransfer());
  await editor.locator("li").nth(4).dispatchEvent("dragstart", { dataTransfer });
  await editor.locator("li").nth(2).dispatchEvent("dragover", { dataTransfer });
  await editor.locator("li").nth(2).dispatchEvent("drop", { dataTransfer });
  await expect(editor.getByRole("status")).toHaveText("Imagen movida a la posición 3.");
  await row.getByRole("button", { name: "Guardar", exact: true }).click();
  await expect(page.getByText("Cambios guardados", { exact: true })).toBeVisible();
  let saved = (await admin.from("product_images").select().eq("product_id", productId).order("sort_order")).data!;
  expect(saved).toHaveLength(5);
  expect(saved.map(image => image.storage_path)).toEqual(expect.arrayContaining(originalPaths));
  expect(saved[0].storage_path).toBe(originalPaths[1]);
  expect(saved[2].alt_text).toBe("IMG_2277.jpg");
  await page.reload();
  await page.getByPlaceholder("Buscar producto...").fill(title);
  await expect(editor.locator("li")).toHaveCount(5);
  await editor.getByRole("button", { name: "Quitar imagen 3", exact: true }).click();
  await row.getByRole("button", { name: "Guardar", exact: true }).click();
  await expect(editor.locator("li")).toHaveCount(4);
  await expect(page.getByText("Cambios guardados", { exact: true })).toBeVisible();
  const beforeFailure = (await admin.from("product_images").select().eq("product_id", productId).order("sort_order")).data!.map(image => image.storage_path);
  await editor.getByLabel("Imágenes", { exact: true }).setInputFiles(files[5]);
  await expect(editor.locator("li")).toHaveCount(5);
  await page.route("**/storage/v1/object/product-images/**", async route => {
    if (route.request().method() === "POST") await route.fulfill({ status: 500, contentType: "application/json", body: JSON.stringify({ statusCode: "500", error: "Upload failed", message: "Fallo de imagen de prueba" }) });
    else await route.fallback();
  });
  await row.getByRole("button", { name: "Guardar", exact: true }).click();
  await expect(page.getByRole("alert", { name: "Notificación" })).toContainText("Fallo de imagen de prueba");
  expect((await admin.from("product_images").select().eq("product_id", productId).order("sort_order")).data!.map(image => image.storage_path)).toEqual(beforeFailure);
  await page.unroute("**/storage/v1/object/product-images/**");
  await row.getByRole("button", { name: "Guardar", exact: true }).click();
  await expect(page.getByText("Cambios guardados", { exact: true })).toBeVisible();
  saved = (await admin.from("product_images").select().eq("product_id", productId).order("sort_order")).data!;
  expect(saved).toHaveLength(5);
  await page.screenshot({ path: ".local/gallery-admin-desktop.png" });
  await page.setViewportSize({ width: 390, height: 844 });
  await editor.scrollIntoViewIfNeeded();
  await page.screenshot({ path: ".local/gallery-admin-mobile.png" });
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true);
  await page.goto(`/producto/?slug=${created.data.slug}`);
  const gallery = page.getByRole("region", { name: "Galería del disco" });
  await expect(gallery.getByText("1 de 5", { exact: true })).toBeVisible();
  await expect(gallery.locator(".detail-gallery-stage img")).toHaveCSS("object-fit", "cover");
  await expect(gallery.getByRole("button", { name: "Imagen anterior" })).toBeDisabled();
  for (let i=0;i<5;i++) {
    await expect(gallery.locator(".detail-gallery-stage img")).toHaveAttribute("src", new RegExp(saved[i].storage_path));
    await expect(gallery.locator(".detail-gallery-stage img")).toBeVisible();
    await expect.poll(() => gallery.locator(".detail-gallery-stage img").evaluate((img: HTMLImageElement) => img.complete && img.naturalWidth > 0)).toBe(true);
    if (i<4) await gallery.getByRole("button", { name: "Imagen siguiente" }).click();
  }
  await expect(gallery.getByRole("button", { name: "Imagen siguiente" })).toBeDisabled();
  await gallery.getByRole("button", { name: "Imagen anterior" }).click();
  await expect(gallery.getByText("4 de 5", { exact: true })).toBeVisible();
  await page.screenshot({ path: ".local/gallery-detail-mobile.png" });
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true);
  await gallery.getByRole("button", { name: "Ampliar imagen 4 de 5" }).click();
  const viewer = page.getByRole("dialog", { name: "Visor ampliado de imágenes" });
  await expect(viewer).toBeVisible();
  await expect(viewer.getByLabel("Nivel de zoom")).toHaveText("100%");
  await viewer.getByRole("button", { name: "Acercar imagen" }).click();
  await viewer.getByRole("button", { name: "Acercar imagen" }).click();
  await expect(viewer.getByLabel("Nivel de zoom")).toHaveText("200%");
  expect(await viewer.locator(".image-viewer-stage").evaluate(element => element.scrollWidth > element.clientWidth && element.scrollHeight > element.clientHeight)).toBe(true);
  await page.screenshot({ path: ".local/product-image-viewer-mobile.png" });
  await viewer.getByRole("button", { name: "Imagen siguiente ampliada" }).click();
  await expect(viewer.getByText("Imagen 5 de 5", { exact: true })).toBeVisible();
  await expect(viewer.getByLabel("Nivel de zoom")).toHaveText("100%");
  await viewer.getByRole("button", { name: "Cerrar imagen ampliada" }).click();
  await expect(viewer).toBeHidden();
  await page.setViewportSize({ width: 1440, height: 1000 });
  await page.screenshot({ path: ".local/gallery-detail-desktop.png" });
  await gallery.getByRole("button", { name: "Ampliar imagen 5 de 5" }).click();
  await expect(viewer).toBeVisible();
  await page.screenshot({ path: ".local/product-image-viewer-desktop.png" });
  await page.keyboard.press("Escape");
  await expect(viewer).toBeHidden();
  await page.goto("/");
  const card = page.locator(".product-card").filter({ hasText: title });
  await expect(card.locator("img")).toHaveAttribute("src", new RegExp(saved[0].storage_path));
  await page.goto("/admin/");
  await page.getByPlaceholder("Buscar producto...").fill(title);
  for (let i=0;i<5;i++) await editor.getByRole("button", { name: "Quitar imagen 1", exact: true }).click();
  await row.getByRole("button", { name: "Guardar", exact: true }).click();
  await expect(page.getByText("Cambios guardados", { exact: true })).toBeVisible();
  expect((await admin.from("product_images").select().eq("product_id", productId)).data).toHaveLength(0);
  await page.goto(`/producto/?slug=${created.data.slug}`);
  await expect(gallery.locator(".detail-gallery-stage img")).toHaveAttribute("src", /lado-a-discos-logo/);
  await expect(gallery.locator(".detail-gallery-controls button")).toHaveCount(0);
  await expect(gallery.getByRole("button", { name: "Ampliar imagen 1 de 1" })).toBeVisible();
});
